### ISSUE TITLE
[DATABASE] - Mongoose Models for IoT Devices, Time-Series Data

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-device#14]
Research on how IoT time series data is represented in MongoDB and what are the best practices for this approach.
- How to organise Data?
- How to filter Data for querying?
- What are the constraints on performance?

Take the inspiration device model as the first iteration.

Implement your findings as an optimized Mongoose model.

### Criteria

- Query efficiency via indexing by:
  - unique device ID (MAC Address)
  - data labels (i.e. temperature)
  - owner
  - timestamp
  - location
- Expandable for more devices, more data labels

One for device info, one for data bucket

**Comment by harsimrat99** [comment]
@DylanOtoole I believe there are a couple of resources that can help get us started for the Mongoose and MongoDB modelling for time series data. 

When working with data that will be logged periodically into the database, also known as time-series data, it is important to create an efficient data storage model. This is important because we need to create an efficient system where data and insights can be queried efficiently. For time series data there a couple of ways to store information in a database; i.e., we can either store 
each data upload as a individual document (JSON object) in MongoDB or separate data by timeframes. For example, we can store data in buckets of fixed time steps. These buckets can be sorted as a minute, hour or day. In this way, instead of storing each uploaded datum as a new model in MongoDB, we can update a previously created model with the new data 

I would appreciate if you could please look at the following resources to help guide your research into this issue and let us know what approach you believe will be the most useful.

[Best Practices for Working with IoT and Time-series Data](https://www.slideshare.net/mongodb/mongodb-world-2019-best-practices-for-working-with-iot-and-timeseries-data) (Slide 22)

[Modeling temporal aspects of sensor data for MongoDB NoSQL database](https://journalofbigdata.springeropen.com/track/pdf/10.1186/s40537-017-0068-5.pdf) (Page 19 _Schema design for time series: a case study_)

[Schema Design for NoSQL Databases](https://www.mongodb.com/nosql-explained/data-modeling)

**Comment by JLefebvre55** [comment]
@harsimrat99 was this closed by #27 ?

**Comment by harsimrat99** [comment]
@JLefebvre55 I believe we can keep this issue open because I would like the teams to dedicate some more research on how to properly make a data scheme and store data in MongoDB. I would like to see more updates on this issue from @DylanOtoole as we  go along.

**Comment by JLefebvre55** [comment]
Helping out with this. I'll lay out some ideas I've got later
