### ISSUE TITLE
More Frontend-Oriented Routes

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-device#53]
- [ ] Get devices by user
- [ ] Get list of users (?)
- [ ] Get all data by data series (i.e. temperature)

More coming.

**Comment by harsimrat99** [comment]
@Lepabryce please take note of this PR since the "Get devices registered by User" route is required for the frontend to list devices.
The ask is to create an API that is able to return the list of devices registered by a user. The API should also use the auth middleware  to prevent unauthorized access. 
@iWebster28 will be needing this API as part of the frontend PR [#8 ](https://github.com/CloudClub-uoft/iot-webapp/issues/8)

**Comment by harsimrat99** [comment]
@Lepabryce do you have any updates for "Get devices by user"?
